checkoutLocation: "." #OR: replace with another folder name

image:
  file: .gitpod.postgres.Dockerfile # OR: .gitpod.mysql.Dockerfile

# Ports to expose on workspace startup
ports:
  - name: web-app
    description: Symfony Application running
    port: 8000
    onOpen: open-browser # OR: open-preview, notify, ignore
    visibility: private # OR: public
  - name: mysql-default
    description: mysql default port
    port: 3306
    visibility: private
  - name: mysql-secure-default
    description: mysql secure port
    port: 33060
    visibility: private
  - name: postgres-default
    description: postgres port
    port: 5432
    visibility: private

# Commands for execution
tasks:
  - name: Initialize workspace
    before: sh ./bash/initial-setup.sh
    init: echo "==> NO INIT SCRIPT"
    command: echo "==> NO COMMAND SCRIPT"
    openMode: split-right #OR: split-left, tab-after, tab-before